token = "296701087:AAGeT3v4xufoP9qW2W1vX884HEomo7AWKpw"
my_id = 163794402

pict = [
"AgADAgAD-acxGyRQIEuaJGxN84IUCHUTSw0ABGpknex8LA-IL7wQAAEC" #батуты

]

menu = ['меню',
       'хэй, баррель!',
       'новости',
       'расписание',
       'кричалка',
       'музыка',
       'батуты',
       'баррелята',
       'черлидинг как спорт',
       'тренеры']


lst = ["меню",
       "хэй, баррель!",
       "новости",
       "расписание",
       "кричалка",
       "музыка",
       "батуты",
       "баррелята",
       "черлидинг как спорт",
       "тренеры"]


names = ['Аделя Давыдова',
         'Азат Нагимов',
         'Аида Рамазанова',
        'Айдар Фасхутдинов',
        'Алексей Александров',
         'Алексей Пранничук',
        'Алена Обыденная',
         'Анастасия Рукс',
        'Анастасия Таранова',
         'Андрей Обыденный',
        'Артем Назаров',
         'Артур Мартыневский',
        'Вадим Поданев',
         'Валерия Бодрягина',
        'Валерия Легчило',
         'Вероника Булгакова',
         'Виталий Щербаченко',
        'Владимир Деордице',
         'Владислав Малявин',
         'Галина Гикаева',
         'Георгий Пушкарев',
        'Георгий Сыртцев',
         'Даниил Асфандияров',
        'Даниил Краснов',
         'Дмитрий Брянцев',
        'Дмитрий Деордице',
         'Евгения Загуменникова',
        'Екатерина Хрулева ',
         'Иван Левкин',
         'Иван Недоруба',
         'Иван Савкин',
         'Илья Сахновский',
        'Илья Филипов',
         'Константин Кудрик',
         'Кристина Бодрягина',
         'Лилит Оганесян',
        'Магомед Мержоев',
         'Максим Клочай',
         'Марат Кабиров',
         'Наташа Андрусенко',
        'Наташа Архиреева',
         'Никита Стрижак',
         'Николай Курочка',
         'Павел Шатунов',
        'Полина Быкова',
         'Полина Смирнова',
         'Рашид Насыров',
         'Сергей Богатырев',
        'Сергей Килюк',
         'Сергей Попов',
         'Татьяна Маринина',
         'Эгон Розенфельдс',
         'Эльвин Геюшов',
        'Юлия Качкина',
         'Яна Коваленко']

bdays = [
"6 мая",	        #Аделя Давыдова#,
"14 апреля",	    #Азат Нагимов#,
"",	                #Аида Рамазанова#,
"",	                #Айдар Фасхутдинов#,
"",	                #Алексей Александров#,
"",	                #Алексей Праннийчук#,
"",	                #Алена Обыденная#,
"21 ноября",	    #Анастасия Рукс#,
"",	                #Анастасия Таранова#,
"25 марта",	        #Андрей Обыденный#,
"10 июня",	        #Артем Назаров#,
"20 мая",	        #Артур Мартыневский#,
"",	                #Вадим Поданев#,
"",	                #Валерия Бодрягина#,
"26 сентября",	    #Валерия Легчило#,
"31 августа",	    #Вероника Булгакова#,
"28 мая",	        #Виталий Щербаченко#,
"",	                #Владимир Деордице#,
"",	                #Владислав Малявин#,
"",	                #Галина Гикаева#,
"",	                #Георгий Пушкарев#,
"25 июня",      	#Георгий Сыртцев#,
"",	                #Даниил Асфандияров#,
"",	                #Даниил Краснов#,
"29 мая",       	#Дмитрий Брянцев#,
"",	                #Дмитрий Деордице#,
"25 июня", 	        #Евгения Загуменникова#,
"19 октября",   	#Екатерина Хрулева #,
"28 января",    	#Иван Левкин#,
"",	                #Иван Недоруба#,
"",	                #Иван Савкин#,
"",	                #Илья Сахновский#,
"20 февраля",	    #Илья Филипов#,
"22 июля",	        #Константин Кудрик#,
"",	                #Кристина Бодрягина#,
"",	                #Лилит Оганесян#,
"",	                #Магомед Мержоев#,
"12 марта",	        #Максим Клочай#,
"13 сентября",	    #Марат Кабиров#,
"",	                #Наташа Андрусенко#,
"10 февраля ",	    #Наташа Архиреева#,
"",	                #Никита Стрижак#,
"",	                #Николай Курочка#,
"12 июля",	        #Павел Шатунов#,
"16 февраля",   	#Полина Быкова#,
"01 мая",	        #Полина Смирнова#,
"02 февраля",	    #Рашид Насыров#,
"04 октября",   	#Сергей Богатырев#,
"",	                #Сергей Килюк#,
"20 января",	    #Сергей Попов#,
"22 октября",	    #Татьяна Маринина#,
"",	                #Эгон Розенфельдс#,
"",	                #Эльвин Геушев#,
"10 июня",	        #Юлия Качкина#,
"8 сентября"        #Яна Коваленко#
]

tel = [
"",	#Аделя Давыдова#,
"",	#Азат Нагимов#,
"",	                #Аида Рамазанова#,
"",	                #Айдар Фасхутдинов#,
"",	                #Алексей Александров#,
"",	                #Алексей Праннийчук#,
"",	                #Алена Обыденная#,
"89161682433",	    #Анастасия Рукс#,
"",	                #Анастасия Таранова#,
"",             	#Андрей Обыденный#,
"89260500423",      #Артем Назаров#,
"",             	#Артур Мартыневский#,
"",	                #Вадим Поданев#,
"",	                #Валерия Бодрягина#,
"",             	#Валерия Легчило#,
"89688010404",	    #Вероника Булгакова#,
"89808888055",	    #Виталий Щербаченко#,
"",	                #Владимир Деордице#,
"",	                #Владислав Малявин#,
"",	                #Галина Гикаева#,
"",	                #Георгий Пушкарев#,
"",              	#Георгий Сыртцев#,
"",	                #Даниил Асфандияров#,
"",	                #Даниил Краснов#,
"",              	#Дмитрий Брянцев#,
"",	                #Дмитрий Деордице#,
"",              	#Евгения Загуменникова#,
"",             	#Екатерина Хрулева #,
"",             	#Иван Левкин#,
"",	                #Иван Недоруба#,
"",	                #Иван Савкин#,
"",	                #Илья Сахновский#,
"89103099229",	    #Илья Филипов#,
"89169001608",	    #Константин Кудрик#,
"",	                #Кристина Бодрягина#,
"",	                #Лилит Оганесян#,
"",	                #Магомед Мержоев#,
"",             	#Максим Клочай#,
"",              	#Марат Кабиров#,
"",	                #Наташа Андрусенко#,
"89168530415",	    #Наташа Архиреева#,
"",	                #Никита Стрижак#,
"",	                #Николай Курочка#,
"89999838837",    	#Павел Шатунов#,
"89670009933",	    #Полина Быкова#,
"",	                #Полина Смирнова#,
"",	                #Рашид Насыров#,
"",	                #Сергей Богатырев#,
"",	                #Сергей Килюк#,
"",	                #Сергей Попов#,
"89171677645",	    #Татьяна Маринина#,
"",	                #Эгон Розенфельдс#,
"",	                #Эльвин Геушев#,
"",	                #Юлия Качкина#,
"89264728331"       #Яна Коваленко#]
]

photo = [
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Аделя Давыдова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Азат Нагимов#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Аида Рамазанова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Айдар Фасхутдинов#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Алексей Александров#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Алексей Праннийчук#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Алена Обыденная#,
"AgADAgAD_KcxG5KRIEtju7fP8rgdPtk8Sw0ABLSAA0D6JNzbVfQQAAEC",	                #Анастасия Рукс#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Анастасия Таранова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Андрей Обыденный#,
"AgADAgADo6gxG1BdGEtoK2h4kxHY3BMWSw0ABDdPB8e3C_PtC-QQAAEC",             	#Артем Назаров#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Артур Мартыневский#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Вадим Поданев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Валерия Бодрягина#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Валерия Легчило#,
"AgADAgADLKgxG8C0IEtICPXpHLPcuR_lDw4ABIG6k_HH8vcl_N0BAAEC",	                #Вероника Булгакова#,
"AgADAgADKqgxGxv2IEuxXvCBQDx2TMEPSw0ABDHmW-05FolpoMkQAAEC",	                #Виталий Щербаченко#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Владимир Деордице#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Владислав Малявин#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Галина Гикаева#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Георгий Пушкарев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC", 	            #Георгий Сыртцев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Даниил Асфандияров#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Даниил Краснов#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Дмитрий Брянцев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Дмитрий Деордице#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Евгения Загуменникова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Екатерина Хрулева #,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Иван Левкин#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Иван Недоруба#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Иван Савкин#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Илья Сахновский#,
"AgADAgADWagxG3K3IUuPzews52mnXQzSDw4ABOYOqGHlQrgt7uEBAAEC",	                #Илья Филипов#,
"AgADAgADYKkxGw28EUvqNJ0RsZJFkE4USw0ABBqisQbL0jEcm9MQAAEC",	                #Константин Кудрик#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Кристина Бодрягина#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Лилит Оганесян#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Магомед Мержоев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Максим Клочай#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Марат Кабиров#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Наташа Андрусенко#,
"AgADAgADRakxG5QVGUsJ8bnp51nlNPjtDw4ABDZFT1iVTiU0EeIBAAEC",	                #Наташа Архиреева#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Никита Стрижак#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Николай Курочка#,
"AgADAgAD_agxGwgfGUtJHXhjGyQWiJXkDw4ABDkOW2GxZVQ7U-UBAAEC",	                #Павел Шатунов#,
"AgADAgADIKgxG2wfIEsxqqe8tK3UlMcWSw0ABLxFP_4EbAXCtd8QAAEC",	                #Полина Быкова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Полина Смирнова#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",             	#Рашид Насыров#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Сергей Богатырев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Сергей Килюк#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Сергей Попов#,
"AgADAgADM6gxG0BqIEs_LPQSBZUXuGsVSw0ABP1pKombddVhGOQQAAEC",	                #Татьяна Маринина#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Эгон Розенфельдс#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Эльвин Геушев#,
"AgADAgADV6kxGw28EUvtgj53bsTDLx_JDw4ABIHB1oFvir-2xNEBAAEC",	                #Юлия Качкина#,
"AgADAgADQqgxGwHaIUsyHiqmxSmPjFPRDw4ABHrBstagNM61eOUBAAEC"                  #Яна Коваленко#
]



